### ISSUE TITLE
Problème de commit sur Github

### ISSUE THREAD

**Issue by uvsq22008386** [Yingqin-SU/projet_ricochet#1]
Un tout petit soucis apparaît sur Github dans la partie Code donc la ou se trouve nos commit. Il y a deux fois le code(deux fois le programme ricochet_Adel_Jonathan_Yassine_Djibril_Mohamed_Yingqin.py . Donc lors du sync il peut y avoir confusion, je n'ai pas la main sur ça donc je ne peux pas supprimer.

**Comment by YingqinSU** [comment]
Je viens de voir ça, ne t'inquiète pas, je vais en garder un seul dans la nouvelle version du jeu.
