### ISSUE TITLE
Problème d'affiche par rapport à mon écran

### ISSUE THREAD

**Issue by uvsq22008386** [Yingqin-SU/projet_ricochet#2]
Un petit soucis se trouve au niveau de l'affiche des indication sur ma fenêtre graphique. Les phrases "how to move" et "switch robot" sont mal placés. Je ne sais pas si c'est que sur mon pc. Car il faut que le programme a la fin s'adapte à tout les pc, notamment sur ceux des professeurs.

**Comment by YingqinSU** [comment]
ça va être un peu compliqué de s'adapter à tous les écrans puisque les paramètres des écrans sont un peu différent les uns par rapport aux autres.

Ce que je pourrai dire, c'est qu'il faut au moins un écran 1080p, sinon le jeu dépasse la bordure. (Ce sera bien aussi que nous précisons dans le readme)

Je vais mettre la nouvelle version du jeu dans quelques instants, tu me diras ce que tu penses

**Comment by uvsq22008386** [comment]
Problème réglé en adaptant les paramètres d'affiche de l'écran de l'utilisateur.
