### ISSUE TITLE
Problème sur le recommencement d'une nouvelle partie

### ISSUE THREAD

**Issue by uvsq22008386** [Yingqin-SU/projet_ricochet#3]
Un petit soucis détecté encore, mais cette fois sur le jeu. Une fois que on arrive a placer le robot sur sa cible, on obtient un message, ensuite, une fois appuyé sur le bouton central noir(bouton recommencer) il est possible de nouveau de recommencer la partie ainsi que de déplacer les robots il n'y a pas de problème. Mais le score n'est pas remis à zéro donc quand on déplace les robots le score continue à augmenter. L'autre problème est que une fois le robot atteint sa cible, cette fois ci aucun message ne s'affiche.

**Comment by YingqinSU** [comment]
Ceci j'ai également régler dans la nouvelle version mais avec une autre méthode, tu me diras ce que tu pense.
