### ISSUE TITLE
score negatif

### ISSUE THREAD

**Issue by uvsq21910586** [Yingqin-SU/projet_ricochet#4]
Après avoir jouer (=déplacer les bots) et que l'on recommence une partie en appuyant sur le bouton dédié à cette effet au centre du plateau. Le score retrouve sa valeur nulle or lorsque que l'on revient en arrière on s'aperçoit que le score peut prendre des valeurs négatives.

**Comment by uvsq22008386** [comment]
oui justement j'avais vu ce problème, les robots pouvait également s'interposer les uns sur les autres

**Comment by djibril78955** [comment]
j'avais vu le meme aussi

**Comment by djibril78955** [comment]
j'avais vu le meme aussi

**Comment by YingqinSU** [comment]
Je viens de corriger le cas où il y a de score négatif dans la nouvelle version.

Pour l'interposition des robots, je n'ai pas très bien compris mais peut-être qu'il y a un rapport avec le score négatif.
En exécuter mon programme de la nouvelle version, je n'ai pas eu ce soucis de l'interposition.

**Comment by uvsq22008386** [comment]
Oui je pense que c'est en lien avec le score négatif, car je vois un score négatif et ensuite à certains moment les robots qui s'interposent. Mais c'est avec une certaine combinaison de touches, par exemple monter descendre gauche droite puis ensuite faire undo plusieurs fois crée ce bug. Mais je ne l'ai vu que très rarement.

**Comment by YingqinSU** [comment]
Close due problem resolve
